/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ddgame;

/**
 *
 * @author Joe
 */
public class CustomSkillWindow extends javax.swing.JDialog {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	DDGameGui origin;
    /**
     * Creates new form CustomSkillWindow
     */
    public CustomSkillWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
  
        origin = (DDGameGui)parent;
        initComponents();
        try {
        Craft1.setText(origin.curChar.skillNames.get(7).substring(6));
        Craft2.setText(origin.curChar.skillNames.get(8).substring(6));
        Craft3.setText(origin.curChar.skillNames.get(9).substring(6));
        Craft4.setText(origin.curChar.skillNames.get(10).substring(6));
        Craft5.setText(origin.curChar.skillNames.get(11).substring(6));
        Craft6.setText(origin.curChar.skillNames.get(12).substring(6));
        Craft7.setText(origin.curChar.skillNames.get(13).substring(6));
        Knowledge1.setText(origin.curChar.skillNames.get(40).substring(10));
        Knowledge2.setText(origin.curChar.skillNames.get(41).substring(10));
        Knowledge3.setText(origin.curChar.skillNames.get(42).substring(10));
        Knowledge4.setText(origin.curChar.skillNames.get(43).substring(10));
        Knowledge5.setText(origin.curChar.skillNames.get(44).substring(10));
        Knowledge6.setText(origin.curChar.skillNames.get(45).substring(10));
        Knowledge7.setText(origin.curChar.skillNames.get(46).substring(10));
        Knowledge8.setText(origin.curChar.skillNames.get(47).substring(10));
        Perform1.setText(origin.curChar.skillNames.get(52).substring(8));
        Perform2.setText(origin.curChar.skillNames.get(53).substring(8));
        Perform3.setText(origin.curChar.skillNames.get(54).substring(8));
        Perform4.setText(origin.curChar.skillNames.get(55).substring(8));
        Perform5.setText(origin.curChar.skillNames.get(56).substring(8));
        Perform6.setText(origin.curChar.skillNames.get(57).substring(8));
        Profession1.setText(origin.curChar.skillNames.get(58).substring(11));
        Profession2.setText(origin.curChar.skillNames.get(59).substring(11));
        Profession3.setText(origin.curChar.skillNames.get(60).substring(11));
        Profession4.setText(origin.curChar.skillNames.get(61).substring(11));
        Profession5.setText(origin.curChar.skillNames.get(62).substring(11));
        Profession6.setText(origin.curChar.skillNames.get(63).substring(11));
        }
        catch (IndexOutOfBoundsException a) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();
        CraftLabel = new javax.swing.JLabel();
        Craft1 = new javax.swing.JTextField();
        Craft2 = new javax.swing.JTextField();
        Craft3 = new javax.swing.JTextField();
        Craft4 = new javax.swing.JTextField();
        Craft5 = new javax.swing.JTextField();
        Craft6 = new javax.swing.JTextField();
        Craft7 = new javax.swing.JTextField();
        Knowledge1 = new javax.swing.JTextField();
        KnowledgeLabel = new javax.swing.JLabel();
        Knowledge2 = new javax.swing.JTextField();
        Knowledge3 = new javax.swing.JTextField();
        Knowledge4 = new javax.swing.JTextField();
        Knowledge5 = new javax.swing.JTextField();
        Knowledge6 = new javax.swing.JTextField();
        Knowledge7 = new javax.swing.JTextField();
        Knowledge8 = new javax.swing.JTextField();
        Perform1 = new javax.swing.JTextField();
        Perform2 = new javax.swing.JTextField();
        Perform3 = new javax.swing.JTextField();
        Perform4 = new javax.swing.JTextField();
        Perform5 = new javax.swing.JTextField();
        Perform6 = new javax.swing.JTextField();
        Profession1 = new javax.swing.JTextField();
        Profession2 = new javax.swing.JTextField();
        Profession3 = new javax.swing.JTextField();
        Profession4 = new javax.swing.JTextField();
        Profession5 = new javax.swing.JTextField();
        Profession6 = new javax.swing.JTextField();
        PerformLabel = new javax.swing.JLabel();
        ProfessionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        CraftLabel.setText("Craft");

        KnowledgeLabel.setText("Knowledge");

        PerformLabel.setText("Perform");

        ProfessionLabel.setText("Profession");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OKButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Knowledge3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Perform3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Profession3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Knowledge4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Perform4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Profession4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Knowledge5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Perform5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Profession5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Craft1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CraftLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Knowledge1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnowledgeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Perform1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PerformLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProfessionLabel)
                                    .addComponent(Profession1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Knowledge2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Perform2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Profession2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Knowledge8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Knowledge7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Craft6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Knowledge6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Perform6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Profession6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CraftLabel)
                    .addComponent(KnowledgeLabel)
                    .addComponent(PerformLabel)
                    .addComponent(ProfessionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Perform6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Profession6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Craft7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Knowledge7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Knowledge8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(OKButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        SkillUpdater();
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    public void SkillUpdater() {
        //craft skills
        origin.curChar.skillNames.set(7, "Craft " + Craft1.getText());
        origin.curChar.skillNames.set(8, "Craft " + Craft2.getText());
        origin.curChar.skillNames.set(9, "Craft " + Craft3.getText());
        origin.curChar.skillNames.set(10, "Craft " + Craft4.getText());
        origin.curChar.skillNames.set(11, "Craft " + Craft5.getText());
        origin.curChar.skillNames.set(12, "Craft " + Craft6.getText());
        origin.curChar.skillNames.set(13, "Craft " + Craft7.getText());
        //knowledge skills
        origin.curChar.skillNames.set(40, "Knowledge " + Knowledge1.getText());
        origin.curChar.skillNames.set(41, "Knowledge " + Knowledge2.getText());
        origin.curChar.skillNames.set(42, "Knowledge " + Knowledge3.getText());
        origin.curChar.skillNames.set(43, "Knowledge " + Knowledge4.getText());
        origin.curChar.skillNames.set(44, "Knowledge " + Knowledge5.getText());
        origin.curChar.skillNames.set(45, "Knowledge " + Knowledge6.getText());
        origin.curChar.skillNames.set(46, "Knowledge " + Knowledge7.getText());
        origin.curChar.skillNames.set(47, "Knowledge " + Knowledge8.getText());
        //Perform Skills
        origin.curChar.skillNames.set(52, "Perform " + Perform1.getText());
        origin.curChar.skillNames.set(53, "Perform " + Perform2.getText());
        origin.curChar.skillNames.set(54, "Perform " + Perform3.getText());
        origin.curChar.skillNames.set(55, "Perform " + Perform4.getText());
        origin.curChar.skillNames.set(56, "Perform " + Perform5.getText());
        origin.curChar.skillNames.set(57, "Perform " + Perform6.getText());
        //Profession Skills
        origin.curChar.skillNames.set(58, "Profession " + Profession1.getText());
        origin.curChar.skillNames.set(59, "Profession " + Profession2.getText());
        origin.curChar.skillNames.set(60, "Profession " + Profession3.getText());
        origin.curChar.skillNames.set(61, "Profession " + Profession4.getText());
        origin.curChar.skillNames.set(62, "Profession " + Profession5.getText());
        origin.curChar.skillNames.set(63, "Profession " + Profession6.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomSkillWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CustomSkillWindow dialog = new CustomSkillWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField Craft1;
    private javax.swing.JTextField Craft2;
    private javax.swing.JTextField Craft3;
    private javax.swing.JTextField Craft4;
    private javax.swing.JTextField Craft5;
    private javax.swing.JTextField Craft6;
    private javax.swing.JTextField Craft7;
    private javax.swing.JLabel CraftLabel;
    private javax.swing.JTextField Knowledge1;
    private javax.swing.JTextField Knowledge2;
    private javax.swing.JTextField Knowledge3;
    private javax.swing.JTextField Knowledge4;
    private javax.swing.JTextField Knowledge5;
    private javax.swing.JTextField Knowledge6;
    private javax.swing.JTextField Knowledge7;
    private javax.swing.JTextField Knowledge8;
    private javax.swing.JLabel KnowledgeLabel;
    private javax.swing.JButton OKButton;
    private javax.swing.JTextField Perform1;
    private javax.swing.JTextField Perform2;
    private javax.swing.JTextField Perform3;
    private javax.swing.JTextField Perform4;
    private javax.swing.JTextField Perform5;
    private javax.swing.JTextField Perform6;
    private javax.swing.JLabel PerformLabel;
    private javax.swing.JTextField Profession1;
    private javax.swing.JTextField Profession2;
    private javax.swing.JTextField Profession3;
    private javax.swing.JTextField Profession4;
    private javax.swing.JTextField Profession5;
    private javax.swing.JTextField Profession6;
    private javax.swing.JLabel ProfessionLabel;
    // End of variables declaration//GEN-END:variables
}
